.TH DWG2DXF 1 "November 2015" "version 1.0"
.SH NAME
dwg2text \- Extract text from dwg/dxf
.SH SYNOPSIS
dwg2text <input> [-b] <-version> <output>
.SH DESCRIPTION
dwg2text is a Console conversor from dwg/dxf to dxf.
.SH OPTIONS
input      dwg or dxf file to extract text
.SH AUTHOR
José F. Soriano - <rallazz@gmail.com>